### PR TITLE
FIX: Remove .DS_Store files 💯

### PR DESCRIPTION
**Pull request by ahmadawais**
Remove the sticky .DS_Store files from the project.

image

BTW use this bash/zsh alias to do that on your next project.

```sh
# Recursively delete `.DS_Store` files
alias rmds="find . -type f -name '*.DS_Store' -ls -delete"
```

### CODE REVIEW

**Comment by zgordon** [comment]
Oh those nasty DS. Thanks!!

**Comment by ahmadawais** [comment]
Feel free to merge it. It shouldn't have any conflicts. I have more PR's coming. Mostly, fixes.

**Comment by tfrommen** [comment]
Duplicate of the already merged #1. 😉

**Comment by zgordon** [comment]
Sweet! Thanks :) just merged

**Pull request merged**
